clients/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	url(r'^$', 'clients.views.client_news'),
 	url(r'^news/$', 'clients.views.client_news'),
	url(r'^profile/$', 'clients.views.client_profile'),
	url(r'^projects/$', 'clients.views.client_projects'),
	url(r'^message/$', 'clients.views.client_message'),
	url(r'^authorpage/$', 'clients.views.client_authorpage'),
    url(r'^projpost/$', 'clients.views.projpost'),
    url(r'^projpost/newproj/$', 'clients.views.newproj'),
    url(r'^draftpost/(\d+)/$', 'clients.views.draftpost'),
    url(r'^draftpost/(\d+)/newdraft/$', 'clients.views.newdraft'),
    url(r'^commpost/(\d+)/$', 'clients.views.commpost'),
    url(r'^commpost/(\d+)/newcomm/$', 'clients.views.newcomm'),

    url(r'^profilepost/$', 'clients.views.profilepost'),
    url(r'^profilepost/newprofile/$', 'clients.views.newprofile'),

	url(r'^forums/$', 'clients.views.forums'),
	url(r'^forums/topic/(\d+)/$', 'clients.views.topics'),
	url(r'^forums/thread/(\d+)/$', 'clients.views.threads'),
	url(r'^forums/post/(new_thread|reply)/(\d+)/$', 'clients.views.posts'),
	url(r'^forums/reply/(\d+)/$', 'clients.views.reply'),
	url(r'^forums/new_thread/(\d+)/$', 'clients.views.new_thread'),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


forum/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
	(r'^$', 'forum.views.main'),
	(r'^forum/(\d+)/$', 'forum.views.forum'),
	(r'^thread/(\d+)/$', 'forum.views.thread'),
	
	(r'^post/(new_thread|reply)/(\d+)/$', 'forum.views.post'),
	(r'^reply/(\d+)/$', 'forum.views.reply'),
	(r'^new_thread/(\d+)/$', 'forum.views.new_thread'),
)

tale_teller/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    (r'^clients/', include('clients.urls')),
	(r'^forum/', include('forum.urls')),
	
    url(r'^admin/', include(admin.site.urls)),
	url(r'^home/$', 'tale_teller.views.home'),
    url(r'^$', 'tale_teller.views.home'),
	url(r'^bio/$', 'tale_teller.views.bio'),
	url(r'^testimonials/$', 'tale_teller.views.testimonials'),
	url(r'^services/$', 'tale_teller.views.services'),
	url(r'^resources/$', 'tale_teller.views.resources'),
	url(r'^kaylynnespauls/$', 'tale_teller.views.kaylynnespauls'),
	
	
	url(r'^accounts/login/$', 'tale_teller.views.login'),
	url(r'^accounts/auth/$', 'tale_teller.views.auth_view'),
	url(r'^accounts/loggedin/$', 'tale_teller.views.loggedin'),
	url(r'^accounts/invalid/$', 'tale_teller.views.invalid_login'),
	url(r'^accounts/logout/$', 'tale_teller.views.logout'),
	
	
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from string import join
from tale_teller.settings import MEDIA_ROOT

class Forum(models.Model):
	title = models.CharField(max_length=60)
	description = models.TextField(max_length = 10000)

	def __unicode__(self):
		return self.title

	def num_posts(self):
		return ([t.num_posts() for t in self.thread_set.all()])

	def last_post(self):
		if self.thread_set.count():
			last = None
			for t in self.thread_set.all():
				l = t.last_post()
				if l:
					if not last: last = l
					elif l.created > last.created: last = l
			return last

class Thread(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    forum = models.ForeignKey(Forum)

    def __unicode__(self):
        return unicode(self.creator) + " - " + self.title

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count() -1

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("created")[0]

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add = True)
    creator = models.ForeignKey(User, blank=True, null=True)
    thread = models.ForeignKey(Thread)
    body = models.TextField(max_length=10000)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.thread, self.title)

    def short(self):
        return u"%s - %s\n%s" % (self.creator, self.title, self.created.strftime("%b %d, %I:%M %p"))
    short.allow_tags = True

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from string import join


DEVELOPMENTAL_EDITING = 'DE'
LINE_EDITING = 'LE'
COPY_EDITING = 'CE'
CREATIVE_CONSULTING = 'CC'

EDITING_CHOICES = (
    (DEVELOPMENTAL_EDITING, 'Developmental Editing'),
    (LINE_EDITING, 'Line Editing'),
    (COPY_EDITING, 'Copy Editing'),
    (CREATIVE_CONSULTING, 'Creative Consulting'),
)


# def get_name():
#     return User.get_short_name()
# Create your models here.
class Transaction(models.Model):
    client = models.ForeignKey(User, blank=True, null=True)
    service = models.CharField(max_length=2, choices=EDITING_CHOICES, default=DEVELOPMENTAL_EDITING)
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    pages = models.DecimalField(max_digits=10, decimal_places=1)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)
    date = models.DateField(auto_now=False, auto_now_add=False)
    def __unicode__(self):
        return unicode(self.client) + '_'+str(self.date.month)+ '-'+str(self.date.day)+ '-'+str(self.date.year)


class Description(models.Model):
    about = models.TextField(blank=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    thumbnail = models.FileField(upload_to = 'profile_pics', blank=True, null=True)

    def __unicode__(self):
        return unicode(self.creator)

clients/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# from PIL import Image as PImage
from os.path import join as pjoin
from django.forms import ModelForm
from forum.models import Forum, Thread, Post
from tale_teller.settings import MEDIA_ROOT, MEDIA_URL
from django.core.context_processors import csrf

from forum.views import main, forum, thread, post
from profiles.views import description, services
from profiles.models import Description, Transaction
from news.views import articles
from projects.views import project, draft, comment
from projects.models import Project, Draft, Comment
import datetime


def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d



@login_required(login_url = '/accounts/login/')
def client_news(request):
    return render_to_response('clientnews.html')

@login_required(login_url = '/accounts/login/')
def client_message(request):
    return render_to_response('clientmessage.html')

@login_required(login_url = '/accounts/login/')
def client_authorpage(request):
    return render_to_response('clientauthorpage.html')


""" Forum Code """
@login_required(login_url = '/accounts/login/')
def forums(request):
    return render_to_response('forums.html', main(request))

@login_required(login_url = '/accounts/login/')
def topics(request, pk):
    return render_to_response('topics.html', forum(request, pk))

@login_required(login_url = '/accounts/login/')	
def threads(request, pk):
    return render_to_response('threads.html', thread(request, pk))


@login_required(login_url = '/accounts/login/')
def posts(request, ptype, pk):
    return render_to_response('posts.html', post(request, ptype, pk))


def new_thread(request, pk):
    p = request.POST
    if p['subject'] and p['body']:
        forum = Forum.objects.get(pk=pk)
        thread= Thread.objects.create(forum=forum, title=p['subject'], creator= request.user)
        Post.objects.create(thread=thread, title=p['subject'], body=p['body'], creator = request.user)
    return HttpResponseRedirect(reverse('clients.views.topics', args=[pk]))


def reply(request, pk):
    p = request.POST
    if p['body']:
        thread = Thread.objects.get(pk=pk)
        post = Post.objects.create(thread=thread, title=p['subject'], body = p['body'], creator = request.user)
    return HttpResponseRedirect(reverse('clients.views.threads', args=[pk]) + '?page=last')

"""End Forum Code """

"""Profile Code """
@login_required(login_url = '/accounts/login/')
def client_profile(request):
    des = {}
    des['transaction'] = services(request)
    des['user_des'] = description(request)
    return render_to_response('clientprofile.html', des)


@login_required(login_url = '/accounts/login/')
def profilepost(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('profilepost.html', c)

@login_required(login_url = '/accounts/login/')
def newprofile(request):
    p = request.POST
    g = request.FILES
    profile = Description.objects.get(creator = request.user)
    profile.about = p['descrip']
    profile.thumbnail = g['profilepic']
    profile.save()
    return HttpResponseRedirect(reverse('clients.views.client_profile'))


"""Projects Code """
@login_required(login_url = '/accounts/login/')
def client_projects(request):
    des = {}
    des['user_des'] = description(request)
    des['project'] = project(request)
    des['draft'] = draft(request)
    des['comment'] = comment(request)
    des['MEDIA_URL'] = MEDIA_URL
    return render_to_response('clientprojects.html', des)


@login_required(login_url = '/accounts/login/')
def projpost(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('projpost.html', c)

@login_required(login_url = '/accounts/login/')
def newproj(request):
    p = request.POST
    post = Project.objects.create(name=p['projname'], description = p['descrip'], date = datetime.date.today(), client = request.user)
    return HttpResponseRedirect(reverse('clients.views.client_projects'))


@login_required(login_url = '/accounts/login/')
def draftpost(request, pk):
    c = {}
    c.update(csrf(request))
    c['pk'] = pk
    return render_to_response('draftpost.html', c)

@login_required(login_url = '/accounts/login/')
def newdraft(request, pk):
    p = request.POST
    g = request.FILES
    post = Draft.objects.create(name = p['draftname'], date = datetime.date.today(), description = p['descrip'], draft_file = g['draftfile'], client = request.user, project = Project.objects.get(pk=pk))
    post.save()
    return HttpResponseRedirect(reverse('clients.views.client_projects'))

@login_required(login_url = '/accounts/login/')
def commpost(request, pk):
    c = {}
    c.update(csrf(request))
    c['pk'] = pk
    return render_to_response('commpost.html', c)

@login_required(login_url = '/accounts/login/')
def newcomm(request, pk):
    p = request.POST
    g = request.FILES
    dr = Draft.objects.get(pk=pk)
    post = Comment.objects.create(body = p['comment'], date = datetime.date.today(), client = request.user, project = dr.project, draft = dr, author=request.user)
    return HttpResponseRedirect(reverse('clients.views.client_projects'))



"""News Code """
@login_required(login_url = '/accounts/login/')
def client_news(request):
    des = {}
    des['article'] = articles(request)
    return render_to_response('clientnews.html', des)

forum/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from forum.models import Forum, Thread, Post
from django.core.paginator import Paginator
from django.core.context_processors import csrf


from tale_teller.settings import MEDIA_ROOT, MEDIA_URL



def main(request):
    """Main listing."""
    forums = Forum.objects.all()
    return dict(forums = forums, user = request.user)
	
	
def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d

def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items

def forum(request, pk):
    """Listing of threads in a forum."""
    threads = Thread.objects.filter(forum=pk).order_by("-created")
    threads = mk_paginator(request, threads, 20)
    forum_name = Forum.objects.get(pk=pk)
    return add_csrf(request, threads=threads, forum_name=forum_name, pk=pk)



def thread(request, pk):
    """Listing of posts in a thread."""
    posts = Post.objects.filter(thread=pk).order_by("created")
    posts = mk_paginator(request, posts, 15)
    title = Thread.objects.get(pk=pk).title
    t = Thread.objects.get(pk=pk)
    return add_csrf(request,posts=posts, pk=pk, title=t.title, forum_pk=t.forum.pk)



def post(request, ptype, pk):
    """Display a post form."""
    action = reverse('clients.views.%s' % ptype, args=[pk])
    if ptype == 'new_thread':
        title = 'Start New Thread'
        subject = ''
    elif ptype == 'reply':
        title = 'Reply'
        subject = 'Re: ' + Thread.objects.get(pk=pk).title
    return add_csrf(request, subject=subject, action=action, title=title)

def new_thread(request, pk):
    # """Start a new thread."""
    p = request.POST
    if p['subject'] and p['body']:
        forum = Forum.objects.get(pk=pk)
        thread=Thread.objects.create(forum=forum, title=p['subject'], creator= request.user)
        Post.objects.create(thread=thread, title=p['subject'], body=p['body'], creator = request.user)
    return HttpResponseRedirect(reverse('forum.views.forum', args=[pk]))


def reply(request, pk):
    # """Reply to a thread."""
    p = request.POST
    if p['body']:
        thread = Thread.objects.get(pk=pk)
        post = Post.objects.create(thread=thread, title=p['subject'], body = p['body'], creator = request.user)
    return HttpResponseRedirect(reverse('forum.views.thread', args=[pk]) + '?page=last')

clients/templates/client_base.html
{% extends "login.html" %}
{% load static %}

{% block other_libs %}
		<link rel = "stylesheet" type = "text/css"  href = "{% static "css/stylesheet_client_base.css" %}">
		<script type = 'text/javascript' src = "{% static "jss/script_clients.js"%}"></script>
		{% block extrastyling %}
		{% endblock %}
{% endblock %}


{% block client_rightblock %}

	<a href = "/clients/news/">
	<div class = "ribbon" id = "newsribbon">
		<img  class = "ribbon_specs"  id = "news" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/news_text.png"%}"/>
	</div>

	<a href = "/clients/profile/">
	<div class = "ribbon" id = "profileribbon">
		<img  class = "ribbon_specs"  id = "profile" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/profile_text.png"%}"/>
	</div>
	</a>
	
	<a href = "/clients/projects/">
	<div class = "ribbon" id = "projectsribbon">
		<img  class = "ribbon_specs"  id = "projects" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/projects_text.png"%}"/>
	</div>
	</a>
	
	<a href = "/clients/forums/">
	<div class = "ribbon" id = "forumsribbon">
		<img  class = "ribbon_specs" id = "authorforums" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/authorforums_text.png"%}"/>
	</div>
	</a>

<!-- 	<a href = "/clients/message/">
	<div class = "ribbon" id = "messageribbon">
		<img  class = "ribbon_specs"  id = "message" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/message_text.png"%}"/>
	</div>
	</a> -->
	
	<a href = "/clients/authorpage/">
	<div class = "ribbon" id = "authorpageribbon">
		<img  class = "ribbon_specs"  id = "authorpage" src = "{% static "images/longer_ribbon.png"%}"/>
		<img class = "link_text" src = "{% static "images/authorpage_text.png"%}"/>
	</div>
	</a>
	
	<a href = "/accounts/logout/">
		<div class = "ribbon" id = "logoutribbon">
			<img  class = "ribbon_specs"  id = "logout" src = "{% static "images/longer_ribbon.png"%}"/>
			<img class = "link_text" src = "{% static "images/logout_text.png"%}"/>
		</div>
	</a>
		
{% endblock %}


{% block client_contentblock %}
<h1>Welcome, and congratulations on being a client!</h1>
{% endblock %}

clients/templates/clientauthorpage.html
{% extends "client_base.html" %}
{% load static %}




{% block client_contentblock %}
<h1 id = "title">Author Page</h1>
<hr/>

</br>
</br>
</br>
<img id = "underconstruction" src = "{% static "images/under_construction2.png"%}" />
{% endblock %}





{% block extrastyling %}
<style>

#underconstruction{
    width: 180px;
    display: block;
    margin-left: auto;
    margin-right: auto;

    }

#title{
    font-family: Centaur;
    margin-top: 50px;
    font-weight: normal;
}
hr{
    height: 1px;
    background-color: black;
    width: 100%;
    margin-left: -5px;
    margin-top: -20px;
}

#authorpage{
width:290px;
}

#authorpageribbon{
left:-30px;
}

</style>
{% endblock %}

clients/templates/clientmessage.html
{% extends "client_base.html" %}
{% load static %}

{% block extrastyling %}
<style>
#message{
width:290px;
}
#messageribbon{
left:-30px;
}

</style>	
{% endblock %}




{% block client_contentblock %}
	<h1>This is your message section.</h1>
{% endblock %}

clients/templates/clientnews.html
{% extends "client_base.html" %}
{% load static %}



{% block client_contentblock %}
<h1 id = "title">News and Updates</h1>
<hr/>

    {%for art in article%}
            <div class = "title_div">
                <h3 class = "article_title">{{art.title}}</h3>
                 <p style = "font-size = 10px; font-family: Centaur; margin:0px">  {{art.date}}</p>

            </div>

            <div class = "article_div">
                {%if art.picture %}
                    {%if art.leftright == "R" %}
                        <div style = "float: right; margin-left: 5px">
                            <img  class = "newspic" src = "/media/{{art.picture}}" />
                            <div style = "text-align: center">{{art.caption}}</div>
                        </div>
                    {%else%}
                        <div style = "float: left; margin-right: 5px">
                            <img  class = "newspic" src = "/media/{{art.picture}}" />
                            <div style = "text-align: center">{{art.caption}}</div>
                        </div>
                    {%endif%}
                {%endif%}
                {{art.body}}
            </div>
    {%endfor%}

    <div class = "heightdiv"></div>

{% endblock %}


{% block extrastyling %}
<style>
.article_title{
    margin-top: 0px;
    margin-bottom:0px;
    font-family: Centaur;
    font-weight: normal;
    }
.title_div{
    margin-top: 0px;

    }

.newspic{
    height: 200px;
    }

.article_div{
    font-family: Centaur;
    height: auto;
    display: inline-block;
    margin-bottom: 50px;
    margin-top: 5px;
    }

#title{
    font-family: Centaur;
    margin-top: 50px;
    font-weight: normal;
}
hr{
    height: 1px;
    background-color: black;
    width: 100%;
    margin-left: -5px;
    margin-top: -20px;
}


#news{
width:290px;
}
#newsribbon{
left:-30px;
}

</style>
{% endblock %}

clients/templates/clientprofile.html
{% extends "client_base.html" %}
{% load static %}

{% block client_contentblock %}

<div id = "container">
    <div id = "outerbox">
        <div id = "profile_left">
            <h1 id = "clientname"> {{user_des.creator.get_full_name}} </h1>
            <hr/>

            {% if user_des.about %}
            <p id = "blurb">{{user_des.about}}</p>
            {% else %}
            <p>You have not uploaded a description.</p>
            {% endif %}

            <br>
            <br>

            <h2 id = "transactions" style = "font-family:Centaur">Transactions</h2>
            <table border = "1" cellpadding = "3" width = 100% cellspacing = "0" id = "transtable">
            <tr>
                <td><b>Date</b></td>
                <td><b>Service</b></td>
                <td><b>Rate</b></td>
                <td><b>Pages</b></td>
                <td><b>Total</b></td>
                <td><b>Paid</b></td>
            </tr>
            {% if transaction %}
                {% for e in transaction %}
                <tr>
                    <td>{{e.date}}</td>
                    <td>{{e.get_service_display}}</td>
                    <td>{{e.rate}}</td>
                    <td>{{e.pages}}</td>
                    <td>{{e.total}}</td>
                    <td>{{e.paid}}</td>
                </tr>
                {%endfor%}

            {% else %}
                <tr>
                    <td colspan = "6">You have no transactions yet.</td>
                </tr>

            {% endif %}

            </table>
        </div>
    </div>



    <div id = "profile_right">

        {% if user_des.thumbnail %}
        <p> <img id = "profile_pic" src = '/media/{{user_des.thumbnail}}'/></p>
        {% else %}

        <p>No profile uploaded.</p>
        {% endif %}


    </div>

</div>

    <div id = "profile_bottom">
        </br>
        </br>
        </br>
        </br>
        </br>
        <p>
        <a href = "{% url 'clients.views.profilepost' %}">Edit Profile</a>
        </p>
    </div>

{% endblock %}



{% block extrastyling %}
<script type = 'text/javascript' src = "{% static "assets/jss/script_profilepg.js"%}"></script>

<style>

    #outerbox{
        float: left;
        width: 100%;
    }
    #profile_left{
        margin-right: 181px;

	}
	#profile_right{
        float: left;
        width: 175px;
        margin-left: -181px;

	}

	#profile_pic{
		border-radius: 10px;
		width: 170px;
		margin-top:35px;
	    display: block;
	    margin-left: auto;
	    margin-right: auto;
    }

	#transtable{
	    margin-right: 10px;

	}

	#profile{
		width:290px;
	}
	#profileribbon{
		left:-30px;
	}
	#clientname{
		font-family: Centaur;
		margin-bottom: -5px;
		margin-top: 50px;
		margin-left:10px;
        font-weight: normal;
	}
	#blurb{
		margin-left: 10px;
		font-family: Centaur;
		font-size: 17px;
	}

	#transactions{
		margin-bottom:3px;
        font-weight: normal;
	}


	hr{
	height: 1px;
	background-color: black;
	}

	#email_div{
		height:300px;
		border: 1px solid black;
        margin-top:35px;
	    display: block;
	    margin-left: 10px;
		}



	#profile_bottom{
		clear: both;
		height: 100px;

	}

</style>
{% endblock %}


clients/templates/clientprojects.html
{% extends "client_base.html" %}
{% load static %}




{% block client_contentblock %}
	<h1 id = "clientname">{{user_des.creator.get_full_name}}</h1>
    <hr/>
    {% if user_des.thumbnail %}
        <p> <img id = "profile_pic" src = '/media/{{user_des.thumbnail}}'/></p>
    {% endif %}
    <a  href="{% url 'clients.views.projpost' %}"><button id = "newproj" type="button">New Project</button></a>
    </br>
    </br>

    {% for proj in project reversed%}



        <div class = "titlediv">


            <div class = "projdes">
                <span class = "projectname">{{proj.name}}</span>
                </br>
                {{proj.description}}
            </div>


            <div class = "postdraftdiv">
                <a class = "postdrafbutton" href = "{% url 'clients.views.draftpost' proj.pk %} "><button id = "newdraft" type="button">Post Draft</button></a>
            </div>

        </div>






        {%for draf in draft%}
            {% if draf.project == proj %}
                <div class = "draftdiv">
                    <a href = "{{ MEDIA_URL }}{{draf.draft_file}}">{{draf.name}}</a>
                    <span style = "float: right">{{draf.date}}</span>

                    <div class = "comment_div">
                        <span style = "font-weight: bold"> {{draf.client}}:</span> {{draf.description}}
                        </br>
                        {%for comm in comment%}
                            {%if comm.draft == draf%}
                                {%if comm.project == proj%}
                                    <span style = "font-weight: bold"> {{comm.author}}:</span> {{comm.body}}
                                    </br>
                                {%endif%}
                            {%endif%}
                        {%endfor%}
                    </div>

                <a href = "{%url 'clients.views.commpost' draf.pk %} "><button class = "newcomment" type="button">Post Comment</button></a>
                </div>

            {% endif %}

        {%endfor%}

    {%endfor%}

        </br>
        </br>
        </br>
        </br>
        </br>
    <div class = "heightdiv"></div>





{% endblock %}


{% block extrastyling %}
    <style>
        .titlediv{
        position: relative;
        margin-bottom: 10px;
        background: linear-gradient(white , #F5DC8A 50%);
        display: inline-block;
        width: 100%;
        min-height: 50px;
        }

        .projdes{
        margin-left: 20px;
        font-family: Centaur;
        width: 80%;
        float: left;
        margin-top: 5px;
        }

        .postdraftdiv{
        display: table-cell;
        vertical-align: middle;
        margin-right: 10px;
        margin-top: 15px;
        float: right;
        bottom:0px;

        }
        .comment_div{
        margin-left: 10px;
        font-family: Centaur;
        }
        .newcomment{
        margin-left: -1px;
        }

        .draftdiv{
        margin-top: 5px;
        margin-bottom:5px;
        margin-left: 20px;

        }


        .projectname{
        font-family: Centaur;
        font-size: 20px;
        }

        .draftname{
        margin-left: 30px;
        font-family: Centaur;
        }



        #newproj{
        }

        hr{
        height: 1px;
        background-color: black;
        width: 80%;
        float: left;
        }

        #profile_pic{
        float: left;
        border-radius: 10px;
        height: 100px;
        margin-top: -50px;
        margin-left: 10px;
        margin-bottom:-30px;

        }

        #clientname{
        font-family: Centaur;
        margin-bottom: -5px;
        margin-top: 50px;
        margin-left:10px;
        font-weight: normal;
        }

        #projects{
        width:290px;
        }
        #projectsribbon{
        left:-30px;
        }
    </style>
{% endblock %}

clients/templates/commpost.html
{% extends "client_base.html" %}
{% load static %}


{% block client_contentblock %}

	<div class="main">
		<div id="reply">
			<div id="rtitle"><h2>{{ title }}</h2></div><br />

			<form action="newcomm/" method="POST" enctype="multipart/form-data"> {% csrf_token %}
			    Comment:<br/><textarea name="comment" id="body"></textarea><br />
				<input type="submit" value="Submit" id="submit" />
			</form>

		</div>
	</div>

{% endblock %}


{% block extrastyling %}
<style>
	#projects{
	width:290px;
	}
	#projectsribbon{
	left:-30px;
	}

    #rtitle{
        font-family: Centaur;
        margin-top: 50px;
        margin-bottom: -30px;

    }

    #body{
    height: 100px;
    width: 80%;

    }
</style>
{% endblock %}